### PR TITLE
fix: disconnect on PoW peer message

### LINKED ISSUE #99: Dropped network connections
### Describe the bug

Logs from the Reth node syncing contained a lot of connections being dropped. These dropped connections were for bootnodes and ended with `Received disconnect command for session reason=Some(SubprotocolSpecific) remote_peer_id=0x...`. This led to a very long completion time for the header stage of the sync pipeline, even needing to be restarted 4 times (first 3 times stopped fetching headers after about 20% completion).
Screenshot 2024-12-21 at 11 21 35
Based on the below screenshot, it looks like a lot of connections are in "Pending Outgoing" and only up to 3 concurrent connections are ever established.
Screenshot 2024-12-21 at 11 22 13
Investigate why connections are being dropped and why outgoing connections are stuck in pending state.

### Steps to reproduce

`RUST_LOG=debug cargo run --bin scroll-reth --features scroll --manifest-path crates/scroll/bin/Cargo.toml -- node --chain scroll-mainnet`

### Node logs

_No response_

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth-scroll-cli Version: 1.1.2
Commit SHA: bb82d3b10960f953c363c2946b5876340a7b0ad9
Build Timestamp: 2024-12-20T09:20:35.578132888Z
Build Features: scroll
Build Profile: release

### What database version are you on?

Current database version: 2
Local database version: 2

### Which chain / network are you on?

scroll-mainnet

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

Default setting

### If you've built Reth from source, provide the full command you used

RUST_LOG=debug cargo run --release --bin scroll-reth --features scroll --manifest-path crates/scroll/bin/Cargo.toml -- node --chain scroll-mainnet --debug.tip 0x60025906c0192f1ad2f3c9f5bbf79c9c03eed3271a258cdb278e8aefd768060f --metrics 0.0.0.0:9001

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by greged93**
Avoid disconnecting peer on `NewBlock` and `NewBlockHashes` peer messages. Feature flag the disconnect and simply log the block hash(es) when "scroll" feature is active.

Resolves #99

### CODE REVIEW

File: crates/net/network/src/manager.rs [hunk 1]
```diff
@@ -542,15 +543,22 @@ impl<N: NetworkPrimitives> NetworkManager<N> {
...
     fn on_peer_message(&mut self, peer_id: PeerId, msg: PeerMessage<N>) {
         match msg {
             PeerMessage::NewBlockHashes(hashes) => {
+                #[cfg(feature = "scroll")]
+                debug!(target: "net", ?hashes, "incoming NewBlockHashes peer message");
+                #[cfg(not(feature = "scroll"))]
                 self.within_pow_or_disconnect(peer_id, |this| {
                     // update peer's state, to track what blocks this peer has seen
                     this.swarm.state_mut().on_new_block_hashes(peer_id, hashes.0)
                 })
```
Comment (frisitano) [inline crates/net/network/src/manager.rs]: Is the `scroll` feature flag suitable here? The `scroll` feature flag has implications for the state commitment logic.

**Review by frisitano — CHANGES_REQUESTED** [review]
I don't think the `scroll` feature flag is suitable here as it has implications for the state commitment types/operations. For example, the `scroll` feature flag is not compatible with the native mpt implementation. 

I wonder if instead of introducing a feature flag we should see if we can modify the `NetworkConfig` to use `PoW` instead of `PoS`? 
https://github.com/scroll-tech/reth/blob/dba97466eda4e5a03bb0ef6e0bcd273850102c83/crates/net/network/src/config.rs#L70-L71

**Review by frisitano — APPROVED** [review]
Looks good! What are the implications here? Does this mean we can sync the node via the existing L2 P2P network after this change?

**Comment by greged93** [comment]
we could sync the node via the L2 P2P before this change, but we were getting a lot of disconnects due to the `NewBlock` and `NewBlockHashes` messages. With this fix, we don't get disconnected anymore.
