### PR TITLE
fix: execution

### LINKED ISSUE #80: L1 message gas used
### Describe the bug

When syncing with `--debug.tip` flag, a gas used error occurs at block 141. This block is the first one containing any L1 message transaction.

### Steps to reproduce

`RUST_LOG=debug c run --bin scroll-reth --features scroll --manifest-path crates/scroll/bin/Cargo.toml -- node --chain scroll-mainnet --debug.tip 0xc29e5f033ad3c2372b9c43c35156dad574940c5cf899a25421cab705aa261a14`

### Node logs

_No response_

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

reth-scroll-cli Version: 1.1.2-dev
Commit SHA: f329794916c1dcaffcf12382502b952ff03da9a0
Build Timestamp: 2024-12-12T15:18:21.138389000Z
Build Features: scroll
Build Profile: debug

### What database version are you on?

Current database version: 2
Local database version: 2

### Which chain / network are you on?

scroll-mainnet

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

`RUST_LOG=debug c run --bin scroll-reth --features scroll --manifest-path crates/scroll/bin/Cargo.toml -- node --chain scroll-mainnet --debug.tip 0xc29e5f033ad3c2372b9c43c35156dad574940c5cf899a25421cab705aa261a14`

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by greged93**
Fixes the following issues with execution:
- load the L1 gas oracle contract in state cache (otherwise [`try_fetch`](https://github.com/scroll-tech/revm/blob/scroll-evm-executor/v49/crates/revm/src/scroll/l1block.rs#L42) method from the `L1BlockInfo` will panic).
- L1 messages do not refund gas and as such gas refunds should be added to the gas used for the block (resolves #80).
- Scroll specific fields (`is_l1_msg` and `rlp_bytes`) from the `TxEnv` should be set for each transaction.
- Set the `state_clear` flag on `State<DB>` if the chain is currently past `Spurious Dragon`. This enables [EIP 161](https://eips.ethereum.org/EIPS/eip-161).

### CODE REVIEW

File: crates/chainspec/src/spec.rs [hunk 1]
```diff
@@ -317,13 +317,6 @@ impl ChainSpec {
 
     /// Get the initial base fee of the genesis block.
     pub fn initial_base_fee(&self) -> Option<u64> {
-        // TODO(scroll): migrate to Chain::scroll() (introduced in https://github.com/alloy-rs/chains/pull/112) when alloy-chains is bumped to version 0.1.48
-        if self.chain == Chain::from_named(NamedChain::Scroll) ||
-            self.chain == Chain::from_named(NamedChain::ScrollSepolia)
-        {
-            return None
-        }
-
```
Comment (frisitano) [inline crates/chainspec/src/spec.rs:326]: Is this not required because the `base_fee_per_gas` is provided in genesis?

File: crates/primitives/src/transaction/compat.rs [hunk 2]
```diff
@@ -12,8 +12,8 @@ pub trait FillTxEnv {
 
 impl FillTxEnv for TransactionSigned {
     fn fill_tx_env(&self, tx_env: &mut TxEnv, sender: Address) {
-        #[cfg(all(feature = "optimism", not(feature = "scroll")))]
-        let envelope = alloy_eips::eip2718::Encodable2718::encoded_2718(self);
+        #[cfg(any(feature = "optimism", feature = "scroll"))]
+        let _envelope = alloy_eips::eip2718::Encodable2718::encoded_2718(self);
```
Comment (frisitano) [inline crates/primitives/src/transaction/compat.rs]: Did we add the `_` because of failing lints? Possibly the correct feature gate would be:
```rust
        #[cfg(any(
            all(feature = "optimism", not(feature = "scroll")),
            all(feature = "scroll", not(feature = "optimism"))
        ))]
```

File: crates/scroll/chainspec/src/lib.rs [hunk 3]
```diff
@@ -72,6 +72,17 @@ impl ScrollChainSpecBuilder {
...
+    /// Construct a new builder from the scroll sepolia chain spec.
+    pub fn scroll_sepolia() -> Self {
+        let mut inner = ChainSpecBuilder::default()
+            .chain(SCROLL_SEPOLIA.chain)
+            .genesis(SCROLL_SEPOLIA.genesis.clone());
+        let forks = SCROLL_SEPOLIA.hardforks.clone();
+        inner = inner.with_forks(forks);
+
+        Self { inner }
+    }
```
Comment (frisitano) [inline crates/scroll/chainspec/src/lib.rs]: Maybe cleaner to have here and above:

```rust
    /// Construct a new builder from the scroll mainnet chain spec.
    pub fn scroll_mainnet() -> Self {
        Self {
            inner: ChainSpecBuilder::default()
                .chain(SCROLL_MAINNET.chain)
                .genesis(SCROLL_MAINNET.genesis.clone())
                .with_forks(SCROLL_MAINNET.hardforks.clone()),
        }
    }

    /// Construct a new builder from the scroll sepolia chain spec.
    pub fn scroll_sepolia() -> Self {
        Self {
            inner: ChainSpecBuilder::default()
                .chain(SCROLL_SEPOLIA.chain)
                .genesis(SCROLL_SEPOLIA.genesis.clone())
                .with_forks(SCROLL_SEPOLIA.hardforks.clone()),
        }
    }
```

What do you think?

File: crates/scroll/state-commitment/src/account.rs [hunk 4]
```diff
@@ -36,3 +39,31 @@ impl From<(Account, B256)> for ScrollTrieAccount {
...
+            storage_root,
+            code_hash: account.code.as_ref().map_or(KECCAK_EMPTY, keccak256),
+            poseidon_code_hash: account
+                .code
+                .as_ref()
+                .map_or(POSEIDON_EMPTY, reth_scroll_primitives::poseidon::hash_code),
+            code_size: account.code.map(|c| c.len()).unwrap_or_default() as u64,
+        }
+    }
+}
```
Comment (frisitano) [inline crates/scroll/state-commitment/src/account.rs:69]: Why do we need this?

**Review by frisitano — COMMENTED** [review]
Left some comments / questions inline.

File: crates/chainspec/src/spec.rs (hunk 1 above)
Comment (greged93) [reply crates/chainspec/src/spec.rs:326]: This was a quick fix in order to retrieve the correct `base_fee_per_gas` for `Scroll` even though `London` is activated at block 0. However, with the introduction of the `make_genesis_header `, which allows for better control and readability this is indeed not needed anymore.

File: crates/scroll/state-commitment/src/account.rs (hunk 4 above)
Comment (greged93) [reply crates/scroll/state-commitment/src/account.rs:69]: this is used [here](https://github.com/scroll-tech/reth/pull/82/files#diff-8e95e1ac11fcfab6e18b8182c4b4889cda75be5209754874f0b29a8a2725e7efR240-R241), which enforces a `Into<ScrollTrieAccount>` bound on the `state_root_ref_unhashed` call.

**Review by frisitano — APPROVED** [review]
LGTM!
